# Generated by Django 3.2.8 on 2021-10-21 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('image', models.CharField(default=None, max_length=300)),
                ('ships_to', models.CharField(default=None, max_length=50)),
                ('quantity', models.PositiveIntegerField(default=None)),
                ('description', models.TextField(default=None, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('weight', models.PositiveIntegerField(default=None)),
                ('categories', models.ManyToManyField(related_name='listings', to='categories.Category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
