# Generated by Django 3.2.8 on 2021-10-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='btc_address',
            field=models.CharField(default=None, max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='vendor_image',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
