# Generated by Django 3.2.8 on 2021-10-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_auto_20211021_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='btc_address',
            field=models.CharField(default='invalid_btc_address', max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='vendor_image',
            field=models.CharField(default='https://www.zuckermanlaw.com/wp-content/uploads/whistleblowing/anonymous-sec-whistleblower.jpg', max_length=300),
        ),
    ]
